/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MealRouteImport } from './routes/meal'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as TimetableRouteImport } from './routes/timetable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MealRoute = MealRouteImport.update({
  id: '/meal',
  path: '/meal',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/meal': typeof MealRoute
  '/notices': typeof NoticesRoute
  '/suggestions': typeof SuggestionsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/meal': typeof MealRoute
  '/notices': typeof NoticesRoute
  '/suggestions': typeof SuggestionsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/meal': typeof MealRoute
  '/notices': typeof NoticesRoute
  '/suggestions': typeof SuggestionsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/calendar'
    | '/dashboard'
    | '/meal'
    | '/notices'
    | '/suggestions'
    | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/calendar'
    | '/dashboard'
    | '/meal'
    | '/notices'
    | '/suggestions'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/calendar'
    | '/dashboard'
    | '/meal'
    | '/notices'
    | '/suggestions'
    | '/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  MealRoute: typeof MealRoute
  NoticesRoute: typeof NoticesRoute
  SuggestionsRoute: typeof SuggestionsRoute
  TimetableRoute: typeof TimetableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal': {
      id: '/meal'
      path: '/meal'
      fullPath: '/meal'
      preLoaderRoute: typeof MealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  MealRoute: MealRoute,
  NoticesRoute: NoticesRoute,
  SuggestionsRoute: SuggestionsRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
